// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq0LB-Udr9qKtXENMI-Rd6uQthQChs0dM',
    appId: '1:384684649813:web:47d99ae1b7100c0049d3dc',
    messagingSenderId: '384684649813',
    projectId: 'usmconect',
    authDomain: 'usmconect.firebaseapp.com',
    storageBucket: 'usmconect.firebasestorage.app',
    measurementId: 'G-WMJN3N37DE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWTXzCFdSI8aJol8uOk3Yx3_m0SlKRrfg',
    appId: '1:384684649813:android:3f8826d1cb07f75849d3dc',
    messagingSenderId: '384684649813',
    projectId: 'usmconect',
    storageBucket: 'usmconect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOGvG-hCRFKeIMEAwgS3Nw7ttPhcXC6gI',
    appId: '1:384684649813:ios:b821cb4c1ea784c049d3dc',
    messagingSenderId: '384684649813',
    projectId: 'usmconect',
    storageBucket: 'usmconect.firebasestorage.app',
    iosBundleId: 'com.example.usmConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOGvG-hCRFKeIMEAwgS3Nw7ttPhcXC6gI',
    appId: '1:384684649813:ios:b821cb4c1ea784c049d3dc',
    messagingSenderId: '384684649813',
    projectId: 'usmconect',
    storageBucket: 'usmconect.firebasestorage.app',
    iosBundleId: 'com.example.usmConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq0LB-Udr9qKtXENMI-Rd6uQthQChs0dM',
    appId: '1:384684649813:web:f509411647f95a9649d3dc',
    messagingSenderId: '384684649813',
    projectId: 'usmconect',
    authDomain: 'usmconect.firebaseapp.com',
    storageBucket: 'usmconect.firebasestorage.app',
    measurementId: 'G-ZLRLF35MR5',
  );
}
